// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DisplayRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisplayRequest) Reset()         { *m = DisplayRequest{} }
func (m *DisplayRequest) String() string { return proto.CompactTextString(m) }
func (*DisplayRequest) ProtoMessage()    {}
func (*DisplayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *DisplayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisplayRequest.Unmarshal(m, b)
}
func (m *DisplayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisplayRequest.Marshal(b, m, deterministic)
}
func (m *DisplayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayRequest.Merge(m, src)
}
func (m *DisplayRequest) XXX_Size() int {
	return xxx_messageInfo_DisplayRequest.Size(m)
}
func (m *DisplayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayRequest proto.InternalMessageInfo

type DisplayResponse struct {
	// displayAscii is the response from the server returning the ascii art
	DisplayAscii         string   `protobuf:"bytes,1,opt,name=displayAscii,proto3" json:"displayAscii,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisplayResponse) Reset()         { *m = DisplayResponse{} }
func (m *DisplayResponse) String() string { return proto.CompactTextString(m) }
func (*DisplayResponse) ProtoMessage()    {}
func (*DisplayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *DisplayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisplayResponse.Unmarshal(m, b)
}
func (m *DisplayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisplayResponse.Marshal(b, m, deterministic)
}
func (m *DisplayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisplayResponse.Merge(m, src)
}
func (m *DisplayResponse) XXX_Size() int {
	return xxx_messageInfo_DisplayResponse.Size(m)
}
func (m *DisplayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisplayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisplayResponse proto.InternalMessageInfo

func (m *DisplayResponse) GetDisplayAscii() string {
	if m != nil {
		return m.DisplayAscii
	}
	return ""
}

type UploadRequest struct {
	// filename is the filename of the asciiArt
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// content is the content of the asciiArt
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *UploadRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UploadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DisplayRequest)(nil), "proto.DisplayRequest")
	proto.RegisterType((*DisplayResponse)(nil), "proto.DisplayResponse")
	proto.RegisterType((*UploadRequest)(nil), "proto.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "proto.UploadResponse")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x58, 0xc1, 0x94,
	0x92, 0x00, 0x17, 0x9f, 0x4b, 0x66, 0x71, 0x41, 0x4e, 0x62, 0x65, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x92, 0x29, 0x17, 0x3f, 0x5c, 0xa4, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x89,
	0x8b, 0x27, 0x05, 0x22, 0xe4, 0x58, 0x9c, 0x9c, 0x99, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19,
	0x84, 0x22, 0xa6, 0xe4, 0xca, 0xc5, 0x1b, 0x5a, 0x90, 0x93, 0x9f, 0x98, 0x02, 0x35, 0x47, 0x48,
	0x8a, 0x8b, 0x23, 0x2d, 0x33, 0x27, 0x35, 0x2f, 0x31, 0x37, 0x15, 0xaa, 0x01, 0xce, 0x17, 0x92,
	0xe0, 0x62, 0x4f, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0x91, 0x60, 0x02, 0x4b, 0xc1, 0xb8, 0x20,
	0xf7, 0xc0, 0x8c, 0x81, 0x58, 0x6e, 0xd4, 0xc9, 0xc8, 0xc5, 0x03, 0xb6, 0x22, 0x18, 0xe2, 0x7e,
	0x21, 0x5b, 0x2e, 0x1e, 0x17, 0x24, 0x9b, 0x85, 0x44, 0x21, 0x3e, 0xd2, 0x43, 0xf5, 0x87, 0x94,
	0x18, 0xba, 0x30, 0xd4, 0x33, 0x56, 0x5c, 0xdc, 0x10, 0x1b, 0x20, 0xba, 0x45, 0xa0, 0xca, 0x50,
	0x1c, 0x2f, 0x25, 0x8a, 0x26, 0x0a, 0xd1, 0x9b, 0xc4, 0x06, 0x16, 0x35, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xb0, 0xe9, 0x7d, 0xcd, 0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AsciiServiceClient is the client API for AsciiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AsciiServiceClient interface {
	// Displays a random ascii art retrieved from a database
	DisplayAscii(ctx context.Context, in *DisplayRequest, opts ...grpc.CallOption) (*DisplayResponse, error)
	// Uploads a clients ascii art to the database
	UploadAscii(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
}

type asciiServiceClient struct {
	cc *grpc.ClientConn
}

func NewAsciiServiceClient(cc *grpc.ClientConn) AsciiServiceClient {
	return &asciiServiceClient{cc}
}

func (c *asciiServiceClient) DisplayAscii(ctx context.Context, in *DisplayRequest, opts ...grpc.CallOption) (*DisplayResponse, error) {
	out := new(DisplayResponse)
	err := c.cc.Invoke(ctx, "/proto.AsciiService/DisplayAscii", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asciiServiceClient) UploadAscii(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, "/proto.AsciiService/UploadAscii", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsciiServiceServer is the server API for AsciiService service.
type AsciiServiceServer interface {
	// Displays a random ascii art retrieved from a database
	DisplayAscii(context.Context, *DisplayRequest) (*DisplayResponse, error)
	// Uploads a clients ascii art to the database
	UploadAscii(context.Context, *UploadRequest) (*UploadResponse, error)
}

// UnimplementedAsciiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAsciiServiceServer struct {
}

func (*UnimplementedAsciiServiceServer) DisplayAscii(ctx context.Context, req *DisplayRequest) (*DisplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisplayAscii not implemented")
}
func (*UnimplementedAsciiServiceServer) UploadAscii(ctx context.Context, req *UploadRequest) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadAscii not implemented")
}

func RegisterAsciiServiceServer(s *grpc.Server, srv AsciiServiceServer) {
	s.RegisterService(&_AsciiService_serviceDesc, srv)
}

func _AsciiService_DisplayAscii_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsciiServiceServer).DisplayAscii(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AsciiService/DisplayAscii",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsciiServiceServer).DisplayAscii(ctx, req.(*DisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsciiService_UploadAscii_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsciiServiceServer).UploadAscii(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AsciiService/UploadAscii",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsciiServiceServer).UploadAscii(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AsciiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AsciiService",
	HandlerType: (*AsciiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisplayAscii",
			Handler:    _AsciiService_DisplayAscii_Handler,
		},
		{
			MethodName: "UploadAscii",
			Handler:    _AsciiService_UploadAscii_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
